Repository srkpi/sc-kpi-web, pull requests merged in 2024-07, with the labels that each got.

#41 API Enhancement
  app/page.tsx
  components/SliderDepartments/index.tsx
  lib/api.ts
Labels: enhancement

#40 Add projects slider
  app/page.tsx
  components/sliders/ArrowLeft/index.tsx
  components/sliders/ArrowRight/index.tsx
  components/sliders/SliderDepartments/DepartmentCardPicture/index.tsx
  components/sliders/SliderDepartments/DepartmentCardText/index.tsx
  components/sliders/SliderDepartments/DepartmentMobileCard/index.tsx
  components/sliders/SliderDepartments/SkeletonDepartmentCard/index.tsx
  components/sliders/SliderDepartments/index.tsx
  components/sliders/SliderProjects/DepartmentCardPicture/index.tsx
  components/sliders/SliderProjects/DepartmentCardText/index.tsx
  components/sliders/SliderProjects/DepartmentMobileCard/index.tsx
  components/sliders/SliderProjects/IconBottomLeftCornerCut/index.tsx
  components/sliders/SliderProjects/SkeletonDepartmentCard/index.tsx
  components/sliders/SliderProjects/index.tsx
  components/sliders/styles.css
  lib/helpers.ts
Labels: feature

#56 ui/table/ add table to ui kit
  app/test/table/page.tsx
  components/ui/table.tsx
Labels: ui

#64 Fix paddings on the Home page layout and header
  app/globals.css
  components/header/header.tsx
  components/sliders/SliderDepartments/DepartmentCardText/index.tsx
Labels: bug

#67 Add register and login page
  app/(auth)/layout.tsx
  app/(auth)/login/_validation/index.ts
  app/(auth)/login/page.tsx
  app/(auth)/register/page.tsx
  app/(auth)/register/validation/index.ts
  app/(auth)/reset-password/[token]/_validation/index.ts
  app/(auth)/reset-password/[token]/page.tsx
  app/(auth)/reset-password/_validation/index.ts
  app/(auth)/reset-password/page.tsx
  app/(client)/layout.tsx
  app/globals.css
  app/layout.tsx
  components/auth/AnimatedBackground/index.tsx
  components/auth/AnimatedLogo/index.tsx
  components/header/components/links.tsx
  components/header/header.tsx
  components/ui/input.tsx
  components/ui/select.tsx
  contexts/AuthContext.tsx
  hooks/useAuth.ts
  hooks/useFetch.ts
  lib/api.ts
  lib/api/api.auth.ts
  lib/api/api.helpers.ts
  lib/swr/fetcher.ts
  package-lock.json
  package.json
  types/auth/index.ts
  types/auth/login.interface.ts
  types/auth/register.interface.ts
  types/auth/token.types.ts
  types/faculty.interface.ts
  types/group.interface.ts
Labels: feature

#70 bug/ fix infinite refreshing if refresh is failed
  contexts/AuthContext.tsx
Labels: bug

#72 admin departments page
  app/admin/departments/[id]/page.tsx
  app/admin/departments/create/page.tsx
  app/admin/departments/page.tsx
  tailwind.config.ts
Labels: admin

#76 enhancement/ remember me implementation
  app/(auth)/login/page.tsx
  app/(auth)/register/page.tsx
  lib/utils/auth.ts
Labels: enhancement
