Repository srkpi/sc-kpi-web, pull requests merged in 2024-08, with the labels that each got.

#86 Add guard for admin pages
  app/admin/layout.tsx
  components/auth/ProtectedAdminRoute/index.tsx
  contexts/AuthContext.tsx
  types/auth/index.ts
  types/auth/role.enum.ts
  types/auth/token.types.ts
Labels: enhancement

#91 Fixing bugs with auth pages
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/register/page.tsx
  app/(auth)/register/validation/index.ts
  app/(client)/clubs/page.tsx
  app/(client)/departments/page.tsx
  app/admin/layout.tsx
  app/globals.css
  app/layout.tsx
  app/not-found.tsx
  components/auth/AnimatedBackground/index.tsx
  components/auth/selects/FacultySelect/index.tsx
  components/auth/selects/GroupSelect/index.tsx
  components/sliders/SliderDepartments/DepartmentCardText/index.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/toast/toast.tsx
  lib/swr/fetcher.ts
Labels: bug

#93 enhancement/image-quality
  app/admin/departments/[id]/page.tsx
  app/admin/departments/create/page.tsx
  app/admin/layout.tsx
  components/admin/create-project-modal.tsx
  components/admin/edit-project-modal.tsx
  components/auth/AnimatedLogo/index.tsx
  components/club-or-department/club-or-department.tsx
  components/footer/footer.tsx
  components/header/header.tsx
  components/sliders/SliderDepartments/DepartmentCardPicture/index.tsx
  components/sliders/SliderDepartments/DepartmentMobileCard/index.tsx
  components/sliders/SliderProjects/DepartmentCardPicture/index.tsx
  components/sliders/SliderProjects/DepartmentMobileCard/index.tsx
Labels: enhancement

#102 ui/badge
  components/ui/badge.tsx
Labels: ui
