Repository srkpi/sc-kpi-web, pull requests merged in 2024-10, with the labels that each got.

#118 feature/new-home-page: add new slider to home page, add services.
  app/(client)/page.tsx
  components/header/header.tsx
  components/sliders/SliderMainPageDepartments/index.tsx
  components/sliders/styles.css
  public/images/blue-hedgehog.svg
  types/service.interface.ts
Labels: feature

#133 bug/fix-slider-images-dublicating
  components/sliders/SliderProjects/DepartmentCardPicture/index.tsx
  components/sliders/SliderProjects/DepartmentMobileCard/index.tsx
  components/sliders/SliderProjects/index.tsx
Labels: bug

#157 admin/services
  app/admin/constants.tsx
  app/admin/services/[id]/page.tsx
  app/admin/services/create/page.tsx
  app/admin/services/page.tsx
  types/service.ts
Labels: admin

#153 enhancement/schedule
  app/(client)/schedule-importer/components/schedule-import.tsx
  app/(client)/schedule-importer/components/schedule-table.tsx
  app/(client)/schedule-importer/components/schedule.tsx
Labels: enhancement
