Repository srkpi/sc-kpi-web, pull requests merged in 2025-04, with the labels that each got.

#271 Add pre-commit hooks for ESLint and Prettier using Husky
  .husky/pre-commit
  package-lock.json
  package.json
Labels: feature

#276 Fix admin actions for editing clubs, services and departments
  app/actions/club.actions.ts
  app/actions/department.actions.ts
  app/actions/service.actions.ts
  app/admin/clubs/[id]/EditClubPage.tsx
  app/admin/clubs/create/page.tsx
  app/admin/departments/[id]/EditDepartmentPage.tsx
  app/admin/services/[id]/EditServicePage.tsx
  components/clubs/club-card.tsx
  constants/club-categories.ts
  lib/client.ts
  types/departments.ts
Labels: admin

#291 Fix header links overlapping
  app/(client)/layout.tsx
  components/header/components/links.tsx
  components/header/header.tsx
Labels: enhancement, ui

#292 added schedule import page
  app/(client)/schedule-importer/components/schedule-import.tsx
  app/(client)/schedule-importer/import/page.tsx
Labels: enhancement

#295 Fix Critical Authorization Bypass Vulnerability in Next.js
  package-lock.json
Labels: dependencies

#297 Added robots.txt and sitemap
  public/robots.txt
  public/sitemap.xml
Labels: SEO

#311 Added OG image
  app/layout.tsx
Labels: SEO
